name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub will use an Ubuntu environment to run this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version to use

      - name: Install dependencies
        run: npm install  # Install the Node.js dependencies

      - name: Run tests
        run: npm test  # Run the tests (if any)

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@13.234.30.251 << 'EOF'
            # Ensure the correct directory is used (root directory)
            cd /home/ec2-user/my-node-app || exit
            # Pull the latest code from the repository
            git pull origin main
            # Install dependencies
            npm install
            # Install pm2 if not already installed
            npm install pm2 -g
            # Restart the application using pm2
            pm2 restart app || pm2 start app.js --name app
          EOF

